linters-settings:
  depguard:
      rules:
        main:
          files:
            - $all
          deny:
            - pkg: reflect
              desc: "avoid reflect"
        test:
          files:
            - $all
          deny:
            - pkg: reflect
              desc: "avoid reflect"
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - fmt.Printf
      - fmt.Println
      - fmt.Fprintf
      - fmt.Fprintln
      - (*github.com/telemachus/humane/internal/buffer.Buffer).WriteByte
      - (*github.com/telemachus/humane/internal/buffer.Buffer).WriteString
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    disabled-checks:
      - hugeParam
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - paralleltest
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  issues-exit-code: 1
  skip-dirs:
    - internal
