name: humane test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go: ['1.19', '1.20']
    name: humane test (using go ${{ matrix.go }} on ${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - run: make test
